# -*- coding: utf-8 -*-
"""TaskTrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-uEIzEZmHrTm4xX_-62wA9m2EG_k1ds
"""

class Task:
    pass
class TaskTracker:
    pass

def main():
    pass

if __name__ == "__main__":
    main()